AttendanceSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),

]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core.views import *


app_name = 'core'

urlpatterns = [
    path('', LoginView.as_view(), name='user-login'),
    path('login', LoginView.as_view(), name='user-login'),
    path('home', AdminHomeView.as_view(), name='home'),
    path('user-home', UserHomeView.as_view(), name='user-home'),
    path('user-logout/', UserLogout, name='user-logout'),
    path('user-register/', UserRegistrationView.as_view(), name='user-register'),
    path('attendance-request/', AttendanceRequestView.as_view(), name='attendance-request'),
    path('approve-attendance/<str:user_id>', ApproveAttendanceView.as_view(), name='approve-attendance'),
]

core/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from .managers import UserManager

# Create your models here.


USER_TYPE = (
    ("Admin", "Admin"),
    ("Student", "Student"),
    ("Teacher", "Teacher"),
)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_joined = models.DateTimeField(auto_now_add=True)
    user_type = models.CharField(max_length=20, choices=USER_TYPE)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    address = models.TextField()
    subscribed = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']


class Attendance(models.Model):
    user = models.ForeignKey('core.User', on_delete=models.PROTECT)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True, null=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

core/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class UserRegistrationForm(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name', 'user_type']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserLogin(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from core.models import *
from datetime import date
from .forms import *
from .decorators import *



# Create your views here.


class AdminHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'core/admin_home.html'
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'

    def get_context_data(self, **kwargs):
        users = Attendance.objects.filter(approved=False)
        context = {'users': users,}
        return context


class UserHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'core/index.html'
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'

    def get_context_data(self, **kwargs):
        attendances = Attendance.objects.filter(user=self.request.user)
        context = {'attendances': attendances,}
        return context


class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    initial = {'key': 'value'}
    template_name = 'core/user_register.html'
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            messages.success(request, 'Account was created for ' + email)
            return redirect('core:user-login')
        return render(request, self.template_name, {'form': form})


class LoginView(TemplateView):
    form_class = UserLogin
    initial = {'key': 'value'}
    template_name = 'core/login.html'
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=username, password=password)
        if user is not None:
            login(request, user)
            if(request.user.user_type == "Admin"):
                return redirect('core:home')
            else:
                return redirect('core:user-home')

        else:
            messages.info(request, 'Username OR Password is Incorrect')
        return render(request, 'core/login.html', {'form': form})


def UserLogout(request):
    logout(request)
    return redirect('core:user-login')


class AttendanceRequestView(LoginRequiredMixin, TemplateView):
    # template_name = 'core/index.html'
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'

    def post(self, request, *args, **kwargs):
        today = date.today()
        if Attendance.objects.filter(user=request.user, date=today).exists():
            messages.info(request, 'Request Already Sent')
            return redirect('core:user-home')
        else:
            user = Attendance.objects.create(user=request.user)
            messages.info(request, 'Request Sent Successfully')
            return redirect('core:user-home')
        return redirect('core:user-home')


class ApproveAttendanceView(LoginRequiredMixin, TemplateView):
    template_name = 'core/admin_home.html'
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'

    def get(self, request, user_id, *args, **kwargs):

        user = Attendance.objects.filter(user=user_id).update(approved=True)
        messages.info(request, 'Attendance Marked!')
        return redirect('core:home')

templates/core/add.html
{% extends 'core/main.html' %}
{% block title %}Add{% endblock %}
{% load static%}

{% block content %}
<br><br><br>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
        <div class="container mt-5">
            <h1>Add Grocery List</h1>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" class="form-control" placeholder="Item name" name="item_name" required="True" />
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" class="form-control" placeholder="Item quantity" name="quantity" required="True" />
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select class="form-control" name="item_status">
                        <option value="PENDING">PENDING</option>
                        <option value="BOUGHT">BOUGHT</option>
                        <option value="NOT AVAILABLE">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" class="form-control" placeholder="Date" name="date" required="True">
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-danger">
                </div>
            </form>
        </div>
{% endblock %}

templates/core/admin_home.html
{% extends 'core/main.html' %}
{% block title %}Admin Home{% endblock %}
{% load static%}

{% block content %}
    <br><br>
    
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
        <div class="mt-5">
            
            <table class="table table-bordered">
                <thead>
                <tr>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Date</th>
                  <th scope="col">Time</th>
                  <th scope="col">User Type</th>
                  <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <tr>
                          <th scope="row">{{ user.user.first_name }}</th>
                          <td>{{ user.user.last_name }}</td>
                          <td>{{ user.user.email }}</td>
                          <td>{{ user.date }}</td>
                          <td>{{ user.time }}</td>
                          <td>{{ user.user.user_type }}</td>
                          <td>
                              <a class="btn btn-warning" href="{% url 'core:approve-attendance' user.user.id %}">Approve</a>
                          </td>
                          
                        </tr>
                    {% endfor %}
                
                </tbody>
            </table>
        </div>
{% endblock %}

templates/core/index.html
{% extends 'core/main.html' %}
{% block title %}Home{% endblock %}
{% load static%}

{% block content %}
    <br><br><br><br>
    {% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
    <center>
        <form action="{% url 'core:attendance-request' %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" value="Send Attendance Request">
            
        </form>
    </center>

<br><br>
        <div class="mt-5">
            <table class="table table-bordered">
                <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Time</th>
                  <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                    {% for att in attendances %}
                        <tr>
                            <td>{{ att.date }}</td>
                            <td>{{ att.time }}</td>
                            <td>
                            {% if att.approved is True %}
                                <a class="btn btn-outline-success">Approved</a>
                            {% elif att.approved is False%}
                                <a class="btn btn-outline-danger">Pending</a>
                            {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                
                </tbody>
            </table>
        </div>

{% endblock %}

templates/core/login.html
{% extends 'core/main.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<br><br><br><br>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<div class="container">
    {{ filter.form }}
    <form action="{% url 'core:user-login' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>

{% endblock %}

templates/core/main.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        {% load static %}
        <title>{% block title %}View List{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% include 'core/navbar.html' %}
        
        {% block content %}

        {% endblock %}

        
    </body>
</html>

templates/core/navbar.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        {% load static %}
        <title>View List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" >
        <a class="navbar-brand" href="#">My Site</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              
              
              {% if request.user.is_authenticated %}

              <a class="btn btn-outline-warning" href="{% url 'core:home' %}">Home</a>&nbsp;
              <a class="btn btn-outline-warning" href="{% url 'core:user-logout' %}">Logout</a>&nbsp;
              {% else %}
              <a class="btn btn-outline-warning" href="{% url 'core:user-login' %}">Login</a>&nbsp;&nbsp;
              <a class="btn btn-outline-primary" href="{% url 'core:user-register' %}">Register</a>&nbsp;
              {% endif %}

          </div>
        </div>
      </nav>
</body>
</html>

templates/core/user_register.html
{% extends 'core/main.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
    <form action="{% url 'core:user-register' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>
{% endblock %}